# 项目地址配置
pro-path:
  list:
    - proName: 测试笔记
      proPath: /download/adoc-temp
    - proName: Java笔记
      proPath: /my_code/InterviewNote
# 字体配置
font:
  linux:
  win: Consolas
  size: 17
  lineSpacing:
